version: "3.5"

x-mysql-props: &mysql-props
  environment:
    MYSQL_DATABASE: test
    MYSQL_USER: root
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

x-php-props: &php-props
  build:
    context: ./docker
    args:
      PHP_VERSION: 7.3
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./:/app
    - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  working_dir: /app
  command: [ "vendor/bin/phpunit" ]
  environment:
    MYSQL_DATABASE: test
    MYSQL_USER: root
    MYSQL_PASS: ""

services:
  mysql57:
    image: mysql:5.7
    <<: *mysql-props

  mysql80:
    image: mysql:8.0
    <<: *mysql-props

  php:
    <<: *php-props
    build:
      context: ./docker
      args:
        PHP_VERSION: 7.3
    depends_on:
      - mysql57
    environment:
      PHP_IDE_CONFIG: serverName=MySQLComeBack
      MYSQL_HOST: mysql57
      MYSQL_DRIVER: pdo_mysql
