name: "Continuous Integration"

on:
  pull_request: null
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit-mysql:
    name: "PHPUnit with MySQL"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        mysql-version:
          - "5.7"
          - "8.0"
        dependencies:
          - "highest"
        include:
          - php-version: "7.3"
            mysql-version: "8.0"
            custom-entrypoint: >-
              --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
          - mysql-version: "5.7"
          - mysql-version: "8.0"
            # https://stackoverflow.com/questions/60902904/how-to-pass-mysql-native-password-to-mysql-service-in-github-actions
            custom-entrypoint: >-
              --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
          - dependencies: "lowest"
            php-version: "7.3"
            mysql-version: "5.7"

    services:
      mysql:
        image: "mysql:${{ matrix.mysql-version }}"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=test
          ${{ matrix.custom-entrypoint }}
        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "mysqli, pdo_mysql"

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit -c ci/github/phpunit/phpunit.xml --coverage-clover=coverage.xml"

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml

  code-style:
    name: "Code style"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: --prefer-dist

      - name: "Run code style check"
        run: "vendor/bin/php-cs-fixer fix --dry-run --ansi --verbose"

  Psalm:
    name: "Psalm"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: --prefer-dist

      - name: "Run code style check"
        run: "vendor/bin/psalm"
